# Whether to use itemlist as a whitelist or not.
whitelist: false

# Which blocks/items shouldn't be stored in the bank.
# If the amount is 0 and the whitelist is false, then that block/item is NON-DEPOSITABLE.
itemlist:
    bedrock:
        '0': 0

# Vault related options.
# Enable vault support?
enableVault: false

# Enable Multi-World support.
# Full - Every world and dimension will have it's own set of accounts (i.e. world1, world1_nether, world1_the_end will have separate accounts).
# Partial - Every world and it's dimensions will have their own set of accounts (i.e. world1, world1_nether, world1_the_end will have the same account).
# None - One account across the whole server.
multiWorld: none

# Database related options
mysql:
    enable: false
    host: 127.0.0.1
    database: database
    port: 3306
    user: user
    pass: password

# Limit the number of pages of items players can have.
# If the amount is 0 then the amount of pages is infinite.
pageLimit: 0

# How much to charge for use of /account
transactionCost: 5

# Whether to check for updates or not.
updateCheck: true
