# List of whitelisted items.
# i.e. minecraft:bedrock
whitelist: [ ]

# List of blacklisted items.
# i.e. minecraft:bedrock
blacklist: [ ]

# Items that have quantity restrictions.
item-restrictions:
  minecraft:bedrock: 0

# Economy support. Requires Vault
enable-economy: false

# How much to charge for use of /account
transaction-cost: 5

# Per world/dimension storage.
multi-world: false

# Storage options
# Storage types: MySQL, MongoDB, SQLite, YAML, JSON, HOCON
format: YAML

# Database options
database:
  address: localhost
  database: database
  user: user
  pass: password
  mongo_uri: ''

# Limit the number of pages of items players can have.
# If the amount is 0 then the amount of pages is infinite.
page-limit: 0
