name: ItemBank
main: ${groupId}.${artifactId}.ItemBank
version: ${version}
description: Virtual chest with configurable limits.
author: Musician101
softdepend: [Vault]
api-version: '1.13'
commands:
    account:
        description: Open an account page.
    itembank:
        description: Base command for the plugin
