name: ItemBank
main: musician101.itembank.ItemBank
version: ${version}
description: Virtual chest with configurable limits.
author: Musician101
softdepend: [Vault]

commands:
    account:
        aliases: [a]
        description: Manage your account.
    itembank:
        aliases: [ib]
        description: Virtual chest with configurable limits.

