package musician101.itembank.listeners;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import musician101.itembank.ItemBank;

import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;

public class PlayerListener implements Listener
{
	public static String template = "# Do not edit this file unless it's absolutely neccessary.\n" + 
			"stone: 0\n"+
			"grass: 0\n"+
			"dirt: 0\n"+
			"cobblestone: 0\n"+
			"wood:\n"+
			" oak: 0\n"+
			" spruce: 0\n"+
			" birch: 0\n"+
			" jungle: 0\n"+
			"sapling:\n"+
			" oak: 0\n"+
			" spruce: 0\n"+
			" birch: 0\n"+
			" jungle: 0\n"+
			"bedrock: 0\n"+
			"sand: 0\n"+
			"gravel: 0\n"+
			"gold_ore: 0\n"+
			"iron_ore: 0\n"+
			"log:\n"+
			" oak: 0\n"+
			" spruce: 0\n"+
			" birch: 0\n"+
			" jungle: 0\n"+
			"leaves:\n"+
			" oak: 0\n"+
			" spruce: 0\n"+
			" birch: 0\n"+
			" jungle: 0\n"+
			"glass: 0\n"+
			"lapis_ore: 0\n"+
			"lapis_block: 0\n"+
			"dispenser: 0\n"+
			"sandstone:\n"+
			" standard: 0\n"+
			" chiseled: 0\n"+
			" smooth: 0\n"+
			"note_block: 0\n"+
			"powered_rail: 0\n"+
			"detector_rail: 0\n"+
			"piston_sticky_base: 0\n"+
			"web: 0\n"+
			"long_grass:\n"+
			" grass: 0\n"+
			" fern: 0\n"+
			"dead_bush: 0\n"+
			"piston_base: 0\n"+
			"wool:\n"+
			" white: 0\n"+
			" orange: 0\n"+
			" magenta: 0\n"+
			" lightBlue: 0\n"+
			" yellow: 0\n"+
			" lime: 0\n"+
			" pink: 0\n"+
			" gray: 0\n"+
			" lightGray: 0\n"+
			" cyan: 0\n"+
			" purple: 0\n"+
			" blue: 0\n"+
			" brown: 0\n"+
			" green: 0\n"+
			" red: 0\n"+
			" black: 0\n"+
			"yellow_flower: 0\n"+
			"red_rose: 0\n"+
			"brown_mushroom: 0\n"+
			"red_mushroom: 0\n"+
			"gold_block: 0\n"+
			"iron_block: 0\n"+
			"step:\n"+
			" stone: 0\n"+
			" sandstone: 0\n"+
			" cobble: 0\n"+
			" brick: 0\n"+
			" stonebrick: 0\n"+
			" netherbrick: 0\n"+
			" quartz: 0\n"+
			"brick: 0\n"+
			"tnt: 0\n"+
			"bookshelf: 0\n"+
			"mossy_cobblestone: 0\n"+
			"obsidian: 0\n"+
			"torch: 0\n"+
			"wood_stairs: 0\n"+
			"chest: 0\n"+
			"diamond_ore: 0\n"+
			"diamond_block: 0\n"+
			"workbench: 0\n"+
			"furnace: 0\n"+
			"ladder: 0\n"+
			"rails: 0\n"+
			"cobblestone_stairs: 0\n"+
			"lever: 0\n"+
			"stone_plate: 0\n"+
			"wood_plate: 0\n"+
			"redstone_ore: 0\n"+
			"redstone_torch_on: 0\n"+
			"stone_button: 0\n"+
			"snow: 0\n"+
			"ice: 0\n"+
			"snow_block: 0\n"+
			"cactus: 0\n"+
			"clay: 0\n"+
			"jukebox: 0\n"+
			"fence: 0\n"+
			"pumpkin: 0\n"+
			"netherrack: 0\n"+
			"soul_sand: 0\n"+
			"glowstone: 0\n"+
			"jack_o_lantern: 0\n"+
			"trap_door: 0\n"+
			"smooth_brick:\n"+
			" standard: 0\n"+
			" mossy: 0\n"+
			" cracked: 0\n"+
			" chiseled: 0\n"+
			"iron_fence: 0\n"+
			"thin_glass: 0\n"+
			"melon_block: 0\n"+
			"vine: 0\n"+
			"fence_gate: 0\n"+
			"brick_stairs: 0\n"+
			"smooth_stairs: 0\n"+
			"mycel: 0\n"+
			"water_lily: 0\n"+
			"nether_brick: 0\n"+
			"nether_fence: 0\n"+
			"nether_brick_stairs: 0\n"+
			"enchantment_table: 0\n"+
			"ender_stone: 0\n"+
			"dragon_egg: 0\n"+
			"redstone_lamp_off: 0\n"+
			"wood_step:\n"+
			" oak: 0\n"+
			" spruce: 0\n"+
			" birch: 0\n"+
			" jungle: 0\n"+
			"sandstone_stairs: 0\n"+
			"emerald_ore: 0\n"+
			"ender_chest: 0\n"+
			"tripwire_hook: 0\n"+
			"emerald_block: 0\n"+
			"spruce_wood_stairs: 0\n"+
			"birch_wood_stairs: 0\n"+
			"jungle_wood_stairs: 0\n"+
			"beacon: 0\n"+
			"cobble_wall:\n"+
			" standard: 0\n"+
			" mossy: 0\n"+
			"wood_button: 0\n"+
			"anvil: 0\n"+
			"trapped_chest: 0\n"+
			"gold_plate: 0\n"+
			"iron_plate: 0\n"+
			"daylight_detector: 0\n"+
			"redstone_block: 0\n"+
			"quartz_ore: 0\n"+
			"hopper: 0\n"+
			"quartz_block:\n"+
			" standard: 0\n"+
			" chiseled: 0\n"+
			" column: 0\n"+
			"quartz_stairs: 0\n"+
			"activator_rails: 0\n"+
			"dropper: 0\n"+
			"iron_spade: 0\n"+
			"iron_pickaxe: 0\n"+
			"iron_axe: 0\n"+
			"flint_and_steel: 0\n"+
			"apple: 0\n"+
			"bow: 0\n"+
			"arrow: 0\n"+
			"coal:\n"+
			" standard: 0\n"+
			" charcoal: 0\n"+
			"diamond: 0\n"+
			"iron_ingot: 0\n"+
			"gold_ingot: 0\n"+
			"iron_sword: 0\n"+
			"wood_sword: 0\n"+
			"wood_spade: 0\n"+
			"wood_pickaxe: 0\n"+
			"wood_axe: 0\n"+
			"stone_sword: 0\n"+
			"stone_spade: 0\n"+
			"stone_pickaxe: 0\n"+
			"stone_axe: 0\n"+
			"diamond_sword: 0\n"+
			"diamond_spade: 0\n"+
			"diamond_pickaxe: 0\n"+
			"diamond_axe: 0\n"+
			"stick: 0\n"+
			"bowl: 0\n"+
			"mushroom_soup: 0\n"+
			"gold_sword: 0\n"+
			"gold_spade: 0\n"+
			"gold_pickaxe: 0\n"+
			"gold_axe: 0\n"+
			"string: 0\n"+
			"feather: 0\n"+
			"sulphur: 0\n"+
			"wood_hoe: 0\n"+
			"stone_hoe: 0\n"+
			"iron_hoe: 0\n"+
			"diamond_hoe: 0\n"+
			"gold_hoe: 0\n"+
			"seeds: 0\n"+
			"wheat: 0\n"+
			"bread: 0\n"+
			"leather_helmet: 0\n"+
			"leather_chestplate: 0\n"+
			"leather_leggings: 0\n"+
			"leather_boots: 0\n"+
			"chainmail_helmet: 0\n"+
			"chainmail_chestplate: 0\n"+
			"chainmail_leggings: 0\n"+
			"chainmail_boots: 0\n"+
			"iron_helmet: 0\n"+
			"iron_chestplate: 0\n"+
			"iron_leggings: 0\n"+
			"iron_boots: 0\n"+
			"diamond_helmet: 0\n"+
			"diamond_chestplate: 0\n"+
			"diamond_leggings: 0\n"+
			"diamdond_boots: 0\n"+
			"gold_helmet: 0\n"+
			"gold_chestplate: 0\n"+
			"gold_leggings: 0\n"+
			"gold_boots: 0\n"+
			"flint: 0\n"+
			"pork: 0\n"+
			"grilled_pork: 0\n"+
			"painting: 0\n"+
			"golden_apple:\n"+
			" standard: 0\n"+
			" notched: 0\n"+
			"sign: 0\n"+
			"wood_door: 0\n"+
			"bucket: 0\n"+
			"water_bucket: 0\n"+
			"lava_bucket: 0\n"+
			"minecart: 0\n"+
			"saddle: 0\n"+
			"iron_door: 0\n"+
			"redstone: 0\n"+
			"snow_ball: 0\n"+
			"boat: 0\n"+
			"leather: 0\n"+
			"milk_bucket: 0\n"+
			"clay_brick: 0\n"+
			"clay_ball: 0\n"+
			"sugar_cane: 0\n"+
			"paper: 0\n"+
			"book: 0\n"+
			"slime_ball: 0\n"+
			"storage_minecart: 0\n"+
			"powered_minecart: 0\n"+
			"egg: 0\n"+
			"compass: 0\n"+
			"fishing_rod: 0\n"+
			"watch: 0\n"+
			"glowstone_dust: 0\n"+
			"raw_fish: 0\n"+
			"cooked_fish: 0\n"+
			"ink_sack:\n"+
			" ink: 0\n"+
			" red: 0\n"+
			" green: 0\n"+
			" cocoa: 0\n"+
			" lapis: 0\n"+
			" purple: 0\n"+
			" cyan: 0\n"+
			" lightGrey: 0\n"+
			" grey: 0\n"+
			" pink: 0\n"+
			" lime: 0\n"+
			" yellow: 0\n"+
			" lightBlue: 0\n"+
			" magenta: 0\n"+
			" orange: 0\n"+
			" bonemeal: 0\n"+
			"bone: 0\n"+
			"sugar: 0\n"+
			"cake: 0\n"+
			"bed: 0\n"+
			"diode: 0\n"+
			"cookie: 0\n"+
			"shears: 0\n"+
			"map: 0\n"+
			"melon: 0\n"+
			"pumpkin_seeds: 0\n"+
			"melon_seeds: 0\n"+
			"raw_beef: 0\n"+
			"cooked_beef: 0\n"+
			"raw_chicken: 0\n"+
			"cooked_chicken: 0\n"+
			"rotten_flesh: 0\n"+
			"ender_pearl: 0\n"+
			"blaze_rod: 0\n"+
			"ghast_tear: 0\n"+
			"gold_nugget: 0\n"+
			"nether_stalk: 0\n"+
			"waterBottle: 0\n"+
			"glass_bottle: 0\n"+
			"spider_eye: 0\n"+
			"fermented_spider_eye: 0\n"+
			"blaze_powder: 0\n"+
			"magma_cream: 0\n"+
			"brewing_stand_item: 0\n"+
			"cauldron_item: 0\n"+
			"eye_of_ender: 0\n"+
			"speckled_melon: 0\n"+
			"exp_bottle: 0\n"+
			"fireball: 0\n"+
			"written_book: 0\n"+
			"emerald: 0\n"+
			"item_frame: 0\n"+
			"flower_pot_item: 0\n"+
			"carrot_item: 0\n"+
			"potato_item: 0\n"+
			"baked_potato: 0\n"+
			"poisonous_potato: 0\n"+
			"empty_map: 0\n"+
			"godlen_carrot: 0\n"+
			"skull_item:\n"+
			" skeleton: 0\n"+
			" wither: 0\n"+
			" zombie: 0\n"+
			" creeper: 0\n"+
			"carrot_stick: 0\n"+
			"nether_star: 0\n"+
			"pumpkin_pie: 0\n"+
			"redstone_comparator: 0\n"+
			"nether_brick_item: 0\n"+
			"quartz: 0\n"+
			"explosive_minecart: 0\n"+
			"hopper_minecart: 0\n"+
			"gold_record: 0\n"+
			"green_record: 0\n"+
			"record_3: 0\n"+
			"record_4: 0\n"+
			"record_5: 0\n"+
			"record_6: 0\n"+
			"record_7: 0\n"+
			"record_8: 0\n"+
			"record_9: 0\n"+
			"record_10: 0\n"+
			"record_11: 0\n"+
			"record_12: 0\n";
	
	ItemBank plugin;
	public PlayerListener(ItemBank plugin)
	{
		this.plugin = plugin;
	}
	
	@EventHandler
	public void onPlayerLogin(PlayerJoinEvent event) throws IOException
	{
		Player player = event.getPlayer();
		File playerFile = new File(ItemBank.dir + "/", player.getName() + ".yml");
		
		if (!playerFile.exists())
		{
			playerFile.createNewFile();
			
			FileWriter fw = new FileWriter(playerFile.getAbsoluteFile());
			BufferedWriter bw = new BufferedWriter(fw);
			bw.write(template);
			bw.close();
		}
	}
}
