# Which blocks/items shouldn't be stored in the bank.
# If the amount is 0 then that block/item is NON-DEPOSITABLE.
blacklist:
    bedrock:
        '0': 0

# Limit the number of pages of items players can have.
# If the amount is 0 then the amount of pages is infinite.
pageLimit: 0

# Whether to check for updates or not.    
updateCheck: true

# Vault related options.
# Enable vault support?
enableVault: false

# How much to charge for use of /account
transactionCost: 5