# Which blocks/items shouldn't be stored in the bank.
# If the amount is 0 then that block/item is NON-DEPOSITABLE.
blacklist:
    bedrock:
        '0': 0

# Limit the number of pages of items players can have.
# If the amount is 0 then the amount of pages is infinite.
pageLimit: 0

# Whether to check for updates or not.    
updateCheck: true

# Vault related options.
# Enable vault support?
enableVault: false

# How much to charge for use of /account
transactionCost: 5

# Language selection.
lang: en

# Which file format to use. This option is ignored if mysql is enabled.
# Supported files: yml, json.
fileType: yml

# Database related options
mysql:
    enable: false
    host: 127.0.0.1
    database: database
    port: 3306
    user: user
    pass: password
