name: ${project.name}
main: ${mainClass}
version: 2.4.2
description: Virtual chest with configurable limits.
author: Musician101
softdepend: [Vault]

commands:
    account:
        aliases: [a]
        description: Manage your account.
    itembank:
        aliases: [ib]
        description: Virtual chest with configurable limits.

