name: ${project.name}
main: ${mainClass}
version: ${project.version}
description: ${project.description}
author: Musician101
softdepend: [Vault]

commands:
    account:
        aliases: [a]
        description: Manage your account.
    itembank:
        aliases: [ib]
        description: Virtual chest with configurable limits.

